name: websiento11
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  pimp_my_button:
    git:
      url: git://github.com/Norbert515/pimp_my_button.git
  flutter:
    sdk: flutter
  popup_menu: 1.0.5
  awesome_dialog: 2.1.0
  page_indicator: 0.4.1
  swipebuttonflutter:
  titled_navigation_bar: 3.5.0
  firebase_auth:
  firebase_core:
  cloud_firestore: 2.5.3
  firebase_database:
  image_picker: 0.8.4+1
  firebase_storage:
  intl:
  flutter_speed_dial: 4.3.0
  shared_preferences: 2.0.7
  flutter_email_sender: 5.0.2
  path_provider:
  rflutter_alert: 1.0.2
  url_launcher: 6.0.10
  flutter_spinkit: 4.1.1
  pdf: 1.4.1
  toast: 0.1.5
  badges: 1.1.0
  google_maps_flutter: 2.0.9
  splashscreen: 1.2.0
  geolocator: 7.6.2
  flutter_credit_card: 0.1.3
  location_permissions:
  persistent_bottom_nav_bar: 4.0.2
  community_material_icon: 5.9.55
  showcaseview:
  flutter_vector_icons: 1.0.0
  web_socket_channel: 1.1.0
  file_picker: 4.2.8
  url_strategy: 0.2.0
  dio: 4.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/llantera_diaz.png
    - images/pizzeria.png
    - images/onelooklogo.png
    - images/call-center.png
    - images/delivery.png
    - images/card.png
    - images/credit.png
    - images/dish.png
    - images/repartamos.png
    - images/hamburguer.png
    - images/taco.png
    - images/pizza.png
    - images/sushi.png
    - images/wing.png
    - images/ancestral.jpg
    - images/siento11.jpg
    - images/siento11.png



  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
